---
service: prismic-lambda-webhook

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-optimize

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  stage: ${opt:stage,self:custom.defaults.stage}
  region: ${opt:region,self:custom.defaults.region}
  profile: ${opt:profile,self:custom.defaults.profile}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:ListTopics
        - sns:CreateTopic
        - sns:Publish
        - sns:Subscribe
      Resource:
        - arn:aws:sns:${self:provider.region}:*:PRISMIC_LAMBDA_WEBHOOK

custom:
  defaults:
    stage: dev
    region: ap-southeast-1
    profile: default

functions:
  webhook:
    description: Handle Prismic.io webhook post and send SNS notification
    handler: functions/webhook.handle
    events:
      - http: POST webhook
