---
service: prismic-lambda-webhook

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-optimize

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  stage: ${opt:stage,self:custom.defaults.stage}
  region: ${opt:region,self:custom.defaults.region}
  profile: ${opt:profile,self:custom.defaults.profile}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:ListTopics
        - sns:CreateTopic
        - sns:Publish
        - sns:Subscribe
        - codepipeline:StartPipelineExecution
      Resource:
        - arn:aws:sns:${self:provider.region}:*:${env:PRISMIC_SNS_TOPIC_NAME}
        - arn:aws:codepipeline:${self:provideo.region}:*:${env:CODEPIPELINE_NAME}

custom:
  defaults:
    stage: dev
    region: ap-southeast-1
    profile: default

functions:
  webhook:
    description: Handle Prismic.io webhook post and send SNS notification
    handler: functions/webhook.handler
    events:
      - http: POST webhook

  build:
    description: Run codepipeline execution triggered by SNS event
    handler: functions/build.handler
    events:
      - sns: ${env:PRISMIC_SNS_TOPIC_NAME}
